(ns proofpeer.proofscript.logic.tests.kernel
  (:use clojure.test)
  (:use proofpeer.proofscript.logic.kernel))

(let [my-tyv   (mk-tyvar         'x)
      my-tyc   (mk-tyconstant    'X)
      my-tyfun (mk-fun-ty        my-tyv my-tyc)
      my-var   (mk-var           0       my-tyv)
      my-const (mk-const         0       my-tyc)
      my-abs   (mk-abs           my-var  my-const)
      my-comb  (mk-app           my-abs  my-var)]
  (do 
    (is (= (dest-var   my-var)   0))
    (is (= (dest-var   my-const) nil))
    (is (= (dest-var   my-comb)  nil))
    (is (= (dest-var   my-abs)   nil))
    (is (= (dest-const my-var)   nil))
    (is (= (dest-const my-const) 0))  
    (is (= (dest-const my-comb)  nil))
    (is (= (dest-const my-abs)   nil))
    (is (= (dest-comb  my-var)   nil))
    (is (= (dest-comb  my-const) nil))  
    (is (= (dest-comb  my-comb)  [my-abs my-var]))
    (is (= (dest-comb  my-abs)   nil))
    (is (= (dest-abs   my-var)   nil))
    (is (= (dest-abs   my-const) nil))  
    (is (= (dest-abs   my-comb)  nil))
    (is (= (dest-abs   my-abs)   [my-var my-const]))
    
    (is (= (type-of my-comb) my-tyc))))
